### PR TITLE
Two more maps

### PR DESCRIPTION
**Pull request by imtn**
I also added these maps to the map selection screen.

### CODE REVIEW

**Comment by cookie966507** [comment]
Somehow the MainMenu unity scene conflicted and it looks like a mess in here (not your fault), so you should duplicate your scene to where it has a different name and then submit a pull request for that scene and then we will manually merge it.

**Comment by cookie966507** [comment]
So don't pull until that happens

**Comment by imtn** [comment]
Don't pull until you've fixed the conflict, or don't pull until I've duplicated the scene? I've duplicated the scene on my end, just waiting for the go-ahead.

**Comment by cookie966507** [comment]
Until you've duplicated so you can go ahead pull and then submit that file as an extra (named something other than MainMenu). It turns out that the git website copied something incorrectly and messed up the scene when I tried to merge earlier.

**Pull request closed without merging**
